import type { Metadata } from "next";
import "@/styles/globals.css";

// import { Geist, Geist_Mono } from "next/font/google";
// import "../styles/globals.css";

import { ThemeProvider } from "@/Providers/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider } from "@/components/ui/sidebar";
import  Header  from "@/components/Header" // If export default is used in Header.tsx then no curly braces are needed
import  AppSidebar  from "@/components/AppSidebar";
import NoteProvider from "@/Providers/NoteProvider";

// export default - Default Export

// Key characteristics:
// Each file can have only one default export
// When importing, you don't use curly braces: import Header from './Header'
// You can rename the component when importing: import MyHeader from './Header'
// The name doesn't matter when importing since you're importing the "default thing"


// export - Named Export

// Key characteristics:
// A file can have multiple named exports
// When importing, you must use curly braces: import { Header } from './Header'
// The import name must match the export name (unless you use aliases)
// You can import multiple named exports: import { Header, Footer } from './components'
// You can rename during import with as: import { Header as PageHeader } from './Header'

export const metadata: Metadata = {
  title: "Study Buddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* A hydration error in React (or Next.js) occurs when the HTML rendered on the server doesn't match the HTML rendered by the client, often due to differences in data or logic between the two environments.  */}

      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NoteProvider>
          <SidebarProvider>
            <AppSidebar />
          <div className="flex min-h-screen w-full flex-col">
          <Header />
          <main className="flex flex-1 flex-col px-4 pt-10 xl:px-">{children}</main>
          </div>
          </SidebarProvider>
            <Toaster />
          </NoteProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
